### ISSUE TITLE
Travis Build Failure with KeyError: ''

### ISSUE THREAD

**Issue by inygy** [callysto/curriculum-notebooks#104]
See PR #103 build failure and accompanying logs. Fails due to ASL-Leap-Motion.ipynb notebook even though there is no clear issue with the notebook itself.

**Comment by cmann** [comment]
The `KeyError`? It's happening for me on when I run the notebook on Callysto Hub too, doesn't seem to be restricted to Travis.

**Comment by inygy** [comment]
My bad, somehow the key error is not present on my fresh callysto hub install or nickurak's hub. However, if I open the notebook on my local Jupyter install I receive the error.

**Comment by nickurak** [comment]
I can get it on my desktop, and we definitely see it in Travis -- so I
think this issue should remain open.

I did look into the error a bit. I can't tell what the code that triggered
it was intending to do -- it creates a widget, but doesn't populate it, so
it start with an empty string, and obviously the dictionary lookup fails
with anything other than a letter of the alphabet -- including if a user
were to enter a string like "Hello".

But the widget is also *disabled*, so there's no way anything *except* the
invalid empty string can be there.

So what's it supposed to be doing, and has it ever worked?

**Comment by nickurak** [comment]
Here's a replacement for that cell that's simpler, smaller, and works, because it handles the incorrect key case, and actually enables the widget. It also removes the code comment (which was factually incorrect).

I don't know if this is what we want or not.

```
dct = dict()
for letter in list('abcdefghijklmnopqrztuvwxyz'):
    dct[letter] = "Orientation for '%s'" % letter

def finder(key):
    if key in dct:
        print(dct[key])
    else:
        print()

interact(finder, key = widgets.Text(placeholder ='a' , description = 'String',disabled = False));
```
