### ISSUE TITLE
Add flag to tell Travis to ignore a notebook or cell

### ISSUE THREAD

**Issue by inygy** [callysto/curriculum-notebooks#108]
Some notebooks have cells which should intentionally fail, such as French-Verb-Conjugation.ipynb. Rather than programming every small unusual case into Travis’ config we want a flag embedded in the notebook which tells Travis to ignore that notebook or cell. Furthermore this flag should be well documented and easily available to our devs.

**Comment by nickurak** [comment]
@inygy Do you think that will suffice, or is it important to have a larger-granularity "blacklist the whole notebook" mechanism?
