### ISSUE TITLE
Data and Sinusoidal Functions notebook

### ISSUE THREAD

**Issue by byrcyb** [callysto/curriculum-notebooks#172]
User reported issue in the Data and Sinusoidal Functions notebook - a mistake in the model for the height of the pendulum.  See screenshot for correction.  Issue involved use of parentheses for the phase shift as well as the value for the period.
![image (16)](https://user-images.githubusercontent.com/7140376/96613322-0b706900-12bc-11eb-9ad1-c62c921165c0.png)

**Comment by misterhay** [comment]
https://github.com/callysto/curriculum-notebooks/pull/176
