### ISSUE TITLE
404 errors for World Bank Climate Data

### ISSUE THREAD

**Issue by misterhay** [callysto/curriculum-notebooks#224]
The notebooks [Climatograph](https://github.com/callysto/curriculum-notebooks/blob/master/Science/Climatograph/climatograph.ipynb) and [Statistics Project / Accessing Data / Climate Monthly](https://github.com/callysto/curriculum-notebooks/blob/master/Mathematics/StatisticsProject/AccessingData/climate-monthly.ipynb) both rely on World Bank climate data. However links generated in those notebooks are returning 404.

As well, my initial exploration of the [API](https://github.com/callysto/curriculum-notebooks/blob/master/Mathematics/StatisticsProject/AccessingData/climate-monthly.ipynb) is also returning 404. Not sure if the problem is the site or me.

**Comment by misterhay** [comment]
We could use [this](https://gist.github.com/misterhay/81ee4bdc42b7a3249a060806fe0aa926) , but it just has 30 year averages and it's just for Canada and provinces/territories.

**Comment by byrcyb** [comment]
I poked around on the API and it looks like they've changed things, and what data is available - i.e. aggregated vs granular, and less historical. I'm not sure if there's another source that was as good as this one but I can look around some more. I know this also impacts the hackathon website so that's on the list of things to change too.

**Comment by lgfunderburk** [comment]
A few datasets that might work, seeing as the API call originally made was for historical data on averages between 1901 and 2016. 

- This contains a series of csvs with data from 1750－2015 by country https://data.world/data-society/global-climate-change-data 
- Another interesting alternative is this R Package "hockeystick" https://cortinah.github.io/hockeystick/ 
- This API allows you to query historical data by latitude and longitude, it requires signing up for a key https://rapidapi.com/community/api/open-weather-map this one seems a bit more granular and might be a good candidate

**Comment by lgfunderburk** [comment]
One thing I am noticing in my search is that free granular data in the form of an API doesn't go too far behind, so looking at a CSV with historical data might be the way to go.

**Comment by misterhay** [comment]
PR created using just Canadian data: https://github.com/callysto/curriculum-notebooks/pull/225

**Comment by byrcyb** [comment]
Issue has been addressed and merged #225
