### ISSUE TITLE
Update to Plotly 3.5.0 Broke Notebooks

### ISSUE THREAD

**Issue by inygy** [callysto/curriculum-notebooks#71]
You can recreate this issue with a simple "run all".

It looks like an issue with plotly 3.0.0 and above. They made non backwards compatible changes with the version updates, resulting in the following notebooks breaking:

- Statistical Reasoning
- Effects of Horizontal and Vertical Translations

@snimpids you are already familiar with the notebooks/code listed above so hopefully it would be quick for you to fix the errors.

**Comment by snimpids** [comment]
I can't replicate the error, even after upgrading plotly with pip. I'm running plotly 3.6.0. However, I have made some adjustments to reduce the size of the notebook.

**Comment by snimpids** [comment]
Update: I replicated the error in horizontal and vertical translations. However, this was one of the first notebooks in the project, so I think I'd rather just reboot it with our newer technologies than fix what's there.

**Comment by inygy** [comment]
How did you replicate the error? Can you provide more details on it/ what was causing it.

You have the go ahead to reboot the notebook, change as much as you want.

**Comment by inygy** [comment]
Resolved by PR #100
