### ISSUE TITLE
Epcor Daily Water Report Error

### ISSUE THREAD

**Issue by inygy** [callysto/curriculum-notebooks#72]
The `Science/concentration-and-ph.ipynb` notebook is broken.

After "run all" cells it returns: `<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>`

If the database is no longer available perhaps we could remove those cells or find an alternative database. Hopefully it is just a verification error, if so either leave a cell in the notebook with instructions for renewing the verification or have it auto-renew.

**Comment by nickurak** [comment]
Confirming that switching to http instead of https corrects the issue -- Epcor's not apparently running these services with SSL enabled at the moment.

I've reached out (again) to somebody I know with Epcor to see if they can look into this.

**Comment by byrcyb** [comment]
I had a look at alternative (data sources) and the Environment Canada National Long-term Water Quality Monitoring Data service (http://data.ec.gc.ca/data/substances/monitor/national-long-term-water-quality-monitoring-data/) might be an option. They have historical data (year 2000+) which gets updated pretty frequently (not daily) and contains physical-chemical parameters such as temperature, pH, alkalinity, major ions, nutrients and metals. As an aside, exploration of this dataset would also make an interesting notebook on its own.
