### ISSUE TITLE
Notebooks failing testing in Travis but not locally

### ISSUE THREAD

**Issue by cmann** [callysto/curriculum-notebooks#77]
The following notebooks are failing only in Travis due to apparent permissions issues when loading external files (see [build #14](https://travis-ci.org/callysto/curriculum-notebooks/builds/486922734)):

* Newton's First Law
* Newton's Third Law
* Introduction to Python

**Comment by cmann** [comment]
Okay, so this seems to be relatively common problem with Docker that I've run into before. The UID of the travis user (2000 from the docs I could find) and the UID of the jupyter user in the docker image (9999) don't match. When the notebook directory is bind mounted into the container the files keep their host owner, group and permissions. Since all the files are 644, reading them is no problem for the jupyter user, but it can't write them which is what the notebooks listed above are trying to do to those external files.

Why this wasn't a problem locally for me is likely related to the fact that I'm running Docker for Windows which handles permissions for bind mounts in strange ways because there's an added SMB/CIFS layer involved. I do start getting the same errors if I copy the files from the bind mount to the container's filesystem so these notebooks should fail locally for users on OSX and Linux.

Solutions-wise it's a little ugly. We can just chown the files in the Travis environment, but doing that to a user's files locally would be unacceptable. Running as root in the container works, but then we're not matching the production environment and in the local case we'd be leaving `.pytest_cache` directories owned by root scattered through the repo. Modifying the UID of the jupyter user would also work, but is non-trivial and while there are utilities that do it, they expect to be baked into the image.

Interestingly though, none of those notebooks actually need to write those external files. The Intro to Python notebook is opening the video files for reading and writing but only reads them. The Newton's Law notebooks are reading `.txt` files, then writing them unmodified to `.html` files and displaying them as iFrames. As far as I can tell, opening the files in Python at all is unnecessary and they can just be displayed directly. I'm going to explore this route for now since it's a more universal solution.

**Comment by inygy** [comment]
> so these notebooks should fail locally for users on OSX and Linux.

I can confirm I saw the same issue running it on my local Arch Linux build.

I have merged #78 and also updated the training manual's troubleshooting section in case other developers encounter this issue in the future. For now I will discourage notebooks which write to files and consider this issue solved. If you are reading this and require a notebook which writes to a file please reopen this issue.
